variables:
  - group: semantic-release

trigger:
  - master

pr:
  - master

jobs:
  - job: commitlint
    pool: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.x
        displayName: Use Node.js 10
      - script: npm ci
        displayName: Install Dependencies
      - script: ./node_modules/.bin/commitlint-azure-pipelines
        displayName: Lint Commits

  - job: test
    pool: Hosted VS2017
    steps:
      # Requires this third party task: https://marketplace.visualstudio.com/items?itemName=azure-cosmosdb.emulator-public-preview
      - task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
        displayName: Run Azure Cosmos DB Emulator
      - task: NodeTool@0
        inputs:
          versionSpec: 8.16.2
        displayName: Use Node.js 8.16.2
      - script: npm ci
        displayName: Install Dependencies
      - script: npm test
        env:
          # The emulator uses a self-signed cert. Disable TLS auth errors
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          COSMOS_ACCOUNT: $(CosmosDbEmulator.Endpoint)
          COSMOS_DATABASE: ci
          # Hardcoded emulator key. Not a real secret
          COSMOS_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        displayName: Run Tests
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: junit.xml
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: coverage\cobertura-coverage.xml
          reportDirectory: coverage

  - job: publish
    dependsOn:
      - commitlint
      - test
    pool: Hosted Ubuntu 1604
    condition:
      and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI',
      'BatchedCI'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.x
        displayName: Use Node.js 10
      - script: npm ci
        displayName: Install Dependencies
      - script: npm run release
        env:
          GH_TOKEN: $(GH_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Publish to NPM
